//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EntityGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   select
        ///    TC.TABLE_NAME,
        ///    TABC.COMMENTS as TABLE_COMMENTS,
        ///    TC.OWNER,
        ///    TC.COLUMN_NAME,
        ///    COLC.COMMENTS as COLUMN_COMMENTS,
        ///    TC.DATA_TYPE,
        ///    TC.DATA_DEFAULT,
        ///    TC.NULLABLE,
        ///    TC.COLUMN_ID,
        ///    TC.DATA_LENGTH,
        ///    TC.DATA_SCALE,
        ///    TC.DATA_PRECISION,
        ///    C.CONSTRAINT_TYPE,
        ///    CC.POSITION
        ///from ALL_TAB_COLUMNS TC
        ///    inner join ALL_TAB_COMMENTS TABC on(
        ///        TABC.OWNER = TC.OWNER
        ///        and TABC.TABLE_NAME = TC.TABLE_NAME
        ///    )
        ///    inner join ALL_COL_COMMENTS COLC  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sql_SelectTableDefinition {
            get {
                return ResourceManager.GetString("Sql_SelectTableDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   select TABLE_NAME from ALL_TABLES where OWNER = :OWNER order by TABLE_NAME に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sql_SelectTableName {
            get {
                return ResourceManager.GetString("Sql_SelectTableName", resourceCulture);
            }
        }
    }
}
